name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${{ secrets.TEST_TOKEN }}
        sh test.sh
    - name: Test
      env:
        TEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo $TEST_TOKEN
